### ISSUE TITLE
fails to import contact module. 

### ISSUE THREAD

**Issue by benmoran56** [Narcolapser/python-o365#18]
When trying to import O365, it fails with an issue importing the contacts module:

Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import O365
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/Desktop/office/lib/python3.4/site-packages/O365/__init__.py", line 21, in <module>
    from contact import Contact
ImportError: No module named 'contact'

This is in a virtual environment, with O365 installed from pip. The git version has the seem issue.

**Comment by Narcolapser** [comment]
Python3 is not currently supported. That appears to be the issue.

**Comment by Narcolapser** [comment]
I fixed this specific error, but python3 is technically still not supported. I would like to move that way in the future, but for the time being this may get you limping along some way.
