### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by Narcolapser** [Narcolapser/python-o365#19]
This should have been python3 from the begining, but I didn't and now I should.

**Comment by benmoran56** [comment]
Are there any specific parts of the codebase that you need help refactoring?

**Comment by Narcolapser** [comment]
huh, prehaps not as much as I imagined. I ran the unit tests using python3 and only contacts, calendar, and attachment were broekn.And calendar and contacts are actually just complaining about a malformed print statement. one sec.

**Comment by Narcolapser** [comment]
appearently with my current suite of tests it is just attachment that needs refactoring. If you could look into what's wrong with it that would be great. thanks!

**Comment by Narcolapser** [comment]
*google searches* appearently I meant @benmoran56 not u/benmoran56. I'm learning github and reddit at the same time. it's easy to get confused. xD

**Comment by skvsree** [comment]
Thanks for this, I am looking forward for this in Python 3

**Comment by benmoran56** [comment]
Sorry, haven't had time to look through the codebase yet. I did give it a short test, and at least the Inbox() functionality seems to work fine on the latest code. (Python 3.4.2, Linux).

**Comment by Narcolapser** [comment]
According to the output of the (unittests)[http://pastebin.com/wupHKrgm] attachment is the only module with issues. A number of them look like they should be quick easy fixes; issues with the change of syntax mostly.
