### ISSUE TITLE
Response 404

### ISSUE THREAD

**Issue by KehaoWu** [Narcolapser/python-o365#22]
When I call getCalendars method in class Schedule, it tell me response 404. 

    https://outlook.office365.com/EWS/OData/Me/Calendars
    <Response [404]>

Could you help me?

**Comment by shaqowski** [comment]
change url to https://outlook.office365.com/api/v1.0/me/calendars

**Comment by KehaoWu** [comment]
Many thanks. :100:

**Comment by Narcolapser** [comment]
Thank you shaqowski.
