### ISSUE TITLE
base64.b64encode returns bytes in Python 3

### ISSUE THREAD

**Issue by tuomas56** [Narcolapser/python-o365#24]
This breaks attachments, since bytes cannot be json serialized.
My current workaround:

``` python
a = Attachment(path=filename)
a.json['ContentBytes'] = a.json['ContentBytes'].decode()
```

**Comment by Narcolapser** [comment]
Fixed with version 0.9.3. Sorry for the huge delay. Didn't have an account to test with until recently. Let me know if you have any further issues.
