### ISSUE TITLE
Missing Message.setBodyHTML() method

### ISSUE THREAD

**Issue by coverband** [Narcolapser/python-o365#28]
Great library, but it's missing a method for sending HTML as email body. I was able to monkey-patch the Message class and add a setBodyHTML() method for my own use where the code only differs for this line:

    self.json['Body']['ContentType'] = 'HTML'

but it would be nice to have this built-in.

**Comment by Narcolapser** [comment]
ah, I see. yea one sec.

**Comment by Narcolapser** [comment]
There you go. You'll have to pull the code down and then run setup.py install to get the changes of course. I'll see if I can get a new version up to pip soon.
