### ISSUE TITLE
Calendar URL

### ISSUE THREAD

**Issue by vernichon** [Narcolapser/python-o365#29]
Hello,

I don't know if it's only for my account, but for me  the good calendar url for the retrival of the calendar GUIDs  is  https://outlook.office365.com/api/v1.0/Me/Calendars  not https://outlook.office365.com/EWS/OData/Me/Calendars (schedule.py line 21)

Thank you for your job

**Comment by Narcolapser** [comment]
no it's probably for everything. But unfortunately I don't have an Office365 address anymore so I can't test anything. Feel free to submit a pull request with the corrected URL.
