### ISSUE TITLE
Turn off logging to file

### ISSUE THREAD

**Issue by sven700c** [Narcolapser/python-o365#34]
How do I turn off logging to o365.log from my script calling the module? I don't have write permission where this script will be deployed and I don't want to have to edit the module.

**Comment by Narcolapser** [comment]
Huh. I didn't prepare for that contingency. Thanks for submitting the issue. I'll see if something can't be done about it when I get the chance.

**Comment by Narcolapser** [comment]
Ok. I think I've got a chance to look at this now. Important detail: Is your script unable to run right now or does it crash because it keeps trying to write to logs it can't write to?

**Comment by sven700c** [comment]
Unless I "touch" a file as root in the rundir beforehand and open up permissions, the script would crash with the following:

./RFQ_Email_Feed_for_Napoleon.py Traceback (most recent call last): File "./RFQ_Email_Feed_for_Napoleon.py", line 18, in <module> from O365 import * File "<frozen importlib._bootstrap>", line 2237, in _find_and_load File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible File "/usr/lib/python3.4/site-packages/O365-0.9-py3.4.egg/O365/__init__.py", line 21, in <module> File "<frozen importlib._bootstrap>", line 2237, in _find_and_load File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible File "/usr/lib/python3.4/site-packages/O365-0.9-py3.4.egg/O365/contact.py", line 7, in <module> File "/usr/lib64/python3.4/logging/__init__.py", line 1732, in basicConfig h = FileHandler(filename, mode) File "/usr/lib64/python3.4/logging/__init__.py", line 999, in __init__ StreamHandler.__init__(self, self._open()) File "/usr/lib64/python3.4/logging/__init__.py", line 1023, in _open return open(self.baseFilename, self.mode, encoding=self.encoding) PermissionError: [Errno 13] Permission denied: '/Net/tokfaspu1/vol_linbinlib/tok/scron_commands/o365.log' 

I rewrote it now so I don't have to use your module, though. As I parse a huge amount of emails with this script, I can't have a file fill up disk space like that. I'd really need to be able to turn off logging to a file completely.

**Comment by Narcolapser** [comment]
Wow. This turned out to be was more simple than I was anticipating. I basically just turned logging off by default. Now I really feel bad about not getting on this sooner. Anyway. Fixed with 0.9.4. Give it a try and let me know if you have any further problems.

**Comment by sven700c** [comment]
Awesome, just what I hoped for. I'll give this a tinker when I find time.
