### ISSUE TITLE
Add support for location in event

### ISSUE THREAD

**Issue by Yenthe666** [Narcolapser/python-o365#39]
HI @Narcolapser,

One feature that I'm missing in this library is the ability to set a location on an event.
When you set the location on the event it will be clearly visible for everybody and it will be attached as it should be.
The same behaviour can be simulated by adding the location (read: a meeting room) as an attendee but it is not entirely correct and in this case the user has to look at all attendees to know the meeting room.
I've started a concept on my own repository but I'm not entirely sure on how to build this.

If I get this correctly I need to make a new class (Location) in which I need to create a function where you can set the location on. This should be imported by Event.py in order to attach it?
I've made a little work in progress here: https://github.com/Yenthe666/python-o365 with most of the code in this PR: https://github.com/Yenthe666/python-o365/commit/01b6f4d6c9f352ff1fdc7f8007dda74a7188dc09

Which should allow to create a new object like this:

```
location = Location(auth=auth)
```

And then somehow the ability to add the location to the Event so it gets pushed in too.
Could you elaborate / give tips on how to further build this? I'm not sure about the details. 😄 

Regards,
Yenthe

**Comment by Narcolapser** [comment]
I'll look a little deeper into this soon. But it looks like what you've got so far is correct. Needs a little more refining, a little more fleshing out. But you are on the right track.

**Comment by Yenthe666** [comment]
@Narcolapser could I ask you for an update please?

**Comment by Narcolapser** [comment]
Sorry, this library just hasn't been a priority since I don't really have a O365 account. Makes it hard to test.

So I think I fixed this when I tended to issue #53. I should have referenced this as well. But as you can see [here](https://github.com/Narcolapser/python-o365/blob/master/O365/event.py#L342) the ability to add a location to events is already in place. This fill your need?

**Comment by Yenthe666** [comment]
Hi @Narcolapser,

No problem, I understand.
So, I added the code to my local `event.py` file and added the following line of code:
`e.setLocation(record.meeting_room_id.email)`, which translates to `my@email.com`.
It always throws errors on `if Location not in self.json:`  though.

Other attempts I did, to be sure:
`e.setLocation({"Address": "my@email.com})` and `e.setLocation({"Location": "my@email.com})`
Perhaps I'm just doing something stupid? 😕 I believe `Location` should be replaced by `loc`?

**Comment by Narcolapser** [comment]
HA! nope, that's my fault. This:
``` python
		if Location not in self.json:
			self.json['Location'] = {"Address":null}
```
Won't ever work. What I meant to put there is:
``` python
		if 'Location' not in self.json:
			self.json['Location'] = {"Address":null}
```
I just commited that change. Try again with that and see if it works now. If it doesn't work, post what error it is throwing, that will help refining the problem.

**Comment by Yenthe666** [comment]
Hi @Narcolapser,

Okay thanks, makes sense.
After testing with:
`e.setLocation('my@email.com` and `e.setLocation({"Address": "my@email.com"})` it both throws this error: 

>   File "/usr/local/lib/python2.7/dist-packages/O365/event.py", line 355, in setLocation
>     self.json['Location'] = {"Address":null}
> NameError: global name 'null' is not defined

**Comment by Narcolapser** [comment]
so funny story, I wrote this code with out actually testing it. (as I mentioned previously, I lack an O365 account) So stupid little things like Location instead of 'Location' and null instead of None slipped by. Just updated it. try it again now.

**Comment by Yenthe666** [comment]
Hi @Narcolapser,

Sorry for the delay on the test - I got sidetracked.
When I add this code:
`e.setLocation({"Address": 'my@email.com})`
I will get the following response from the service:
```
{'attendees': [],
 'auth': (u'my@email.com', u'mypassword'),
 'calendar': None,
 'isNew': False,
 'json': {u'error': {u'code': u'RequestBodyRead',
                     u'message': u"A 'PrimitiveValue' node with non-null value was found when trying to read the value of the property 'Address'; however, a 'StartArray' node, a 'StartObject' node, or a 'PrimitiveValue' node with null value was expected."}}}
```

**Comment by Narcolapser** [comment]
is this a copy paste from your code: 

e.setLocation({"Address": 'my@email.com})

Because you typo-ed. forgot the second '

assuming that {"Address": 'my@email.com'} doesn't work, can you try {"Address": 'my@email.com','DisplayName':'my place'}? that should get it closer to what the code does for the latter example you gave.

And yes. As soon as this is working correctly I push a new version up to pypi.

**Comment by Yenthe666** [comment]
Hi @Narcolapser,

No this was a typo here, it was in fact opened and closed with '.
I did try both `Address` and `DisplayName` as you said but it still gives the same error.

**Comment by Narcolapser** [comment]
ok, thinking about it python should have blown up if that was a typo in your code file. xD

This is very strange, why does one work but not the other? Lets try this, in your local copy of event.py try adding to the setLocation function so it looks like this:

``` python
	if isinstance(loc,dict):
		self.json['Location'] = loc
	else:
		self.json['Location']['DisplayName'] = str(loc)
		
	print('dict value: ' + str(self.json['Location']))
```

then try running both the working argument and the broken arguments and paste what it spits out for both. That should give us an idea of what is different.

**Comment by Yenthe666** [comment]
Hi @Narcolapser, the output after changing to the code example you just gave above my comment (if I do a pprint(vars(e)) looks like this:
```
{'DisplayName': 'Test', 'Address': u'meetingroom1@mycompany.be'}
{'attendees': [],
 'auth': (u'yenthe@mycompany.be', u'mypassword'),
 'calendar': None,
 'isNew': False,
 'json': {u'error': {u'code': u'RequestBodyRead',
                     u'message': u"A 'PrimitiveValue' node with non-null value was found when trying to read the value of the property 'Address'; however, a 'StartArray' node, a 'StartObject' node, or a 'PrimitiveValue' node with null value was expected."}}}
```

The output (with pprint(vars(e)) without your latest suggestion:
```
{'attendees': [],
 'auth': (u'yenthe@mycompany.be', u'mypassword'),
 'calendar': None,
 'isNew': False,
 'json': {u'error': {u'code': u'RequestBodyRead',
                     u'message': u"A 'PrimitiveValue' node with non-null value was found when trying to read the value of the property 'Address'; however, a 'StartArray' node, a 'StartObject' node, or a 'PrimitiveValue' node with null value was expected."}}}

```

**Comment by Narcolapser** [comment]
what's the output with the code and using the known working call: e.setLocation('my@email.com')

**Comment by Yenthe666** [comment]
Only edited some content (such as shortening the ID's) so that they're not public, structure did not change:

```
{'attendees': [],
 'auth': (u'yenthe@mycompany.be', u'mypassword'),
 'calendar': None,
 'isNew': False,
 'json': {u'@odata.context': u"https://outlook.office365.com/api/v1.0/$metadata#Me/Calendars('ASOMEKEY')/Events/$entity",
          u'@odata.etag': u'W/"FTOAoV72vU6Vd5cFAA8OvIcA=="',
          u'@odata.id': u"https://outlook.office365.com/api/v1.0/Users('yenthe@mycompany.be')/Events('AAMkAGExNTZmMWRmLTZhZDgtNGYyZS1iYTY5LWY2Nxz6PZp-JYTYnvgB2VR8LXBwAVM4ChXva9TpV3lwWFfM9BAAAAAAENAAAVM4ChXva9TpV3lwWFfM9BAADwzRrAAAA=')",
          u'Attendees': [{u'EmailAddress': {u'Address': u'attendee1@mycompany.be',
                                            u'Name': u'James'},
                          u'Status': {u'Response': u'None',
                                      u'Time': u'0001-01-01T00:00:00Z'},
                          u'Type': u'Required'},
                         {u'EmailAddress': {u'Address': u'myemail@mycompany.be',
                                            u'Name': u'yenthe'},
                          u'Status': {u'Response': u'None',
                                      u'Time': u'0001-01-01T00:00:00Z'},
                          u'Type': u'Required'}],
          u'Body': {u'Content': u'', u'ContentType': u'Text'},
          u'BodyPreview': u'',
          u'Categories': [],
          u'ChangeKey': u'FTOAoV72vU6Vd5cFhXzcA==',
          u'DateTimeCreated': u'2017-07-12T14:20:05.8213504Z',
          u'DateTimeLastModified': u'2017-07-12T14:20:06.1856441Z',
          u'End': u'2017-07-12T14:19:56Z',
          u'EndTimeZone': u'UTC',
          u'HasAttachments': False,
          u'Id': u'AAMkAGExNTZmMWRmLTZhZDgtNGYyZS1iYTY5LWY2NWRjMWNiZWY5ZABGAAAAAAAxz6PZp-JYTYnvgB2VR8LXBwAVM4ChXva9TENAAAVM4ChXva9TpV3lwWFfM9BAADwzRrAAAA=',
          u'Importance': u'Normal',
          u'IsAllDay': False,
          u'IsCancelled': False,
          u'IsOrganizer': True,
          u'Location': {u'DisplayName': u'meetingroom1@mycompany.be'},
          u'Organizer': {u'EmailAddress': {u'Address': u'yenthe@mycompany.be',
                                           u'Name': u'Yenthe'}},
          u'Recurrence': None,
          u'Reminder': 15,
          u'ResponseRequested': True,
          u'ResponseStatus': {u'Response': u'Organizer',
                              u'Time': u'0001-01-01T00:00:00Z'},
          u'Sensitivity': u'Normal',
          u'SeriesMasterId': None,
          u'ShowAs': u'Busy',
          u'Start': u'2017-07-12T14:19:56Z',
          u'StartTimeZone': u'UTC',
          u'Subject': u'Test',
          u'Type': u'SingleInstance',
          u'WebLink': u'https://outlook.office365.com/owa/?itemid=AAMkAGExNTZmMWRmLTZhZDgtNGYyZS1iYTY5LWY2NWRjMWNiZWY5ZABGAAAAAAAxz6PZp%2FJYTYnvgB2VR8LXBwAVM4ChXva9TpV3lwWFAAVM4ChXva9TpV3lwWFfM9BAADwzRrAAAA%3D&exvsurl=1&path=/calendar/item',
          u'iCalUId': u'040000008200E00074C5B7101A847A78F519FBD201000000000000000010000000C6108DE5ABC4514E82B1D488D2901CD1'}}
```

Looks like it has to be:
```
{u'DisplayName': u'meetingroom1@mycompany.be'},
```

**Comment by Narcolapser** [comment]
try passing that in as the argument and see if it works. I'm trying to figure out if I have doing something that breaks everything with the dict or if the dict just gets slightly malformed or something.

**Comment by Yenthe666** [comment]
Hi @Narcolapser - confirmed.
`e.setLocation({"DisplayName": 'some@email.com})` works.

**Comment by Narcolapser** [comment]
ok. so now the question is why doesn't {"Address": 'my@email.com'}.

hmmm. it looks like it is because "Address" is not a string. see [here](https://msdn.microsoft.com/en-us/office/office365/api/complex-types-for-mail-contacts-calendar#PhysicalAddress).

Try {"LocationEmailAddress": 'my@email.com','DisplayName':'my place'}

**Comment by Narcolapser** [comment]
any luck? if that worked I'll make the necessary changes and then push it to pypi

**Comment by Yenthe666** [comment]
I'll test it tommorow and I'll give you feedback. 😉

**Comment by Yenthe666** [comment]
Hi @Narcolapser,

Sorry for the delay. What you suggested to test:
`e.setLocation({"LocationEmailAddress": self.meeting_room_id.email, "DisplayName": "Test"})`
Which translates to this in JSON:
```
{'attendees': [],
 'auth': (u'tony@mycompany.be', u'mypass'),
 'calendar': <O365.cal.Calendar object at 0x7f752fa1fed0>,
 'json': {'Attendees': [{'EmailAddress': {'Address': u'tony@mycompany.be'}},
                        {'EmailAddress': {'Address': u'yenthe@mycompany.be',
                                          'Name': u'yenthe'}}],
          'End': '2017-07-22T13:00:00-00:00',
          'EndTimeZone': 'UTC',
          'Location': {'DisplayName': 'Test',
                       'LocationEmailAddress': u'room@mycompany.be'},
          'Start': '2017-07-22T11:00:00-00:00',
          'StartTimeZone': 'UTC',
          'Subject': u'Example task 2'}}
```
Which seems to give the following error:
```
failed to append calendar: 'ascii' codec can't encode character u'\xeb' in position 19: ordinal not in range(128)
```

**Comment by Narcolapser** [comment]
Somethings wrong here. Your calendar isn't getting properly translated into a json object. What did you call to get to the json?

**Comment by Yenthe666** [comment]
To print it out? `pprint(vars(e))`
It works fine if I don't pass along `LocationEmailAddress`.

**Comment by Narcolapser** [comment]
Aah, that edit helps. 


hmm. on further inspection, I was looking at the wrong version of the API. V2 instead of V1 which is what this library uses. So in that case, we only have DisplayName (string), Address(complex type), and Coordinates (complex type) to work with. I think the only reasonable option to get started at this point will be to drop the address entirely. Just depend on DisplayName. But lets give this a try:

{'Address':{'City':'Yenthe-vile'},'DisplayName':'my place'}

**Comment by Yenthe666** [comment]
Yep, seems to be working fine. Can you add it in & create a new version please? :clinking_glasses:

**Comment by Narcolapser** [comment]
Alright. new package uploaded, give it a try and verify that it works.

**Comment by Narcolapser** [comment]
it work @Yenthe666?

**Comment by Yenthe666** [comment]
It all seems to work fine 😉 Thanks for the update!

**Comment by Narcolapser** [comment]
Good to hear!

**Comment by Yenthe666** [comment]
Good job 👏
