### ISSUE TITLE
KeyError: 'Body' on setBody method

### ISSUE THREAD

**Issue by Yenthe666** [Narcolapser/python-o365#40]
Hi @Narcolapser,

When you use the setBody function of your library it will generate the following error:
```
  File "/usr/local/lib/python2.7/dist-packages/O365/event.py", line 227, in setBody
    self.json['Body']['Content'] = val
KeyError: 'Body'
```

Coming from this function:
```
	def setBody(self,val):
		'''sets event body content.'''
		self.json['Body']['Content'] = val
```

Example code:
```
from O365 import *
import json
from ppretty import ppretty

auth = ('my.email@company.be', 'myPassword')

schedule = Schedule(auth)
schedule.getCalendars()

cal = schedule.calendars[0]
e = Event(auth=auth, cal=cal)
e.setAttendees({"EmailAddress":{"Address":"my.email@company.be"}})
e.setSubject('Test')
e.setStart('2016-10-10T20:00:00-00:00')
e.setStartTimeZone('UTC')
e.setEnd('2016-10-10T21:00:00-00:00')
e.setEndTimeZone('UTC')
e.setBody('Body content')
print ppretty(e)
e = e.create()
```

Any idea why this happens? If I comment e.setBody it will work fine.

Regards,
Yenthe

**Comment by Narcolapser** [comment]
Yea. I didn't do a sanity check before I tried setting the body. Fixed it. Patch coming soon.

**Comment by leonardodutra** [comment]
to me creating a new event returns this error

leonardo@leonardo-HP-450-Notebook-PC:~/projetos/python-o365/examples/VehicleBookings$ python veh.py 
Traceback (most recent call last):
  File "veh.py", line 2, in <module>
    from printing import *
ImportError: No module named printing

**Comment by Narcolapser** [comment]
Can you open a new issue? thanks.

**Comment by leonardodutra** [comment]
Done boss, thanks!

2017-02-10 18:14 GMT-02:00 Toben Archer <notifications@github.com>:
