### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by ajwillo** [Narcolapser/python-o365#50]
Tying to install on python for windows results in the below

c:\website>pip install python-o365
Collecting python-o365
  Could not find a version that satisfies the requirement python-o365 (from versions: )
No matching distribution found for python-o365

**Comment by Narcolapser** [comment]
what python version?

**Comment by ajwillo** [comment]
2.7 for windows,

also getting same issue in centos

CentOS Linux release 7.3.1611 (Core)

**Comment by emican86** [comment]
try
pip install O365

I think python2.7 may need to install requests, so this line of your output
may be different:
"""
Requirement already satisfied (use --upgrade to upgrade): requests in
c:\apps\wi
npython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages (from O365)
"""

*Here is my output:*
C:\Apps\WinPython-64bit-3.5.2.2\scripts>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64
bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import O365
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'O365'
>>> exit()

C:\Apps\WinPython-64bit-3.5.2.2\notebooks>pip install O365
Collecting O365
  Downloading O365-0.9.5.zip
Requirement already satisfied (use --upgrade to upgrade): requests in
c:\apps\wi
npython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages (from O365)
Building wheels for collected packages: O365
  Running setup.py bdist_wheel for O365 ... done
  Stored in directory:
C:\Users\vm\AppData\Local\pip\Cache\wheels\8f\e7\b4\5ad
8ae2b6365767051a51fede3df910d8e31b1048309a89528
Successfully built O365
Installing collected packages: O365
Successfully installed O365-0.9.5
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.

C:\Apps\WinPython-64bit-3.5.2.2\notebooks>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64
bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import O365
>>> exit()

**Comment by Narcolapser** [comment]
Yes, I believe emican86 is right. have you tried that ajwillo? If that doesn't work I have a theory as to what might be wrong.
