### ISSUE TITLE
ImportError: No module named printing

### ISSUE THREAD

**Issue by leonardodutra** [Narcolapser/python-o365#51]
to me creating a new event returns this error

leonardo@leonardo-HP-450-Notebook-PC:~/projetos/python-o365/examples/VehicleBookings$ python veh.py
Traceback (most recent call last):
File "veh.py", line 2, in 
from printing import *
ImportError: No module named printing

**Comment by Narcolapser** [comment]
I just commited a change (74e17ffdf813b4edf062a900d907f08819d03873) that should fix it. What you are trying to do though doesn't seem to make sense. Are you calling veh.py to create a new event?

**Comment by leonardodutra** [comment]
Hi, thank you for your answer, yes, i tried to get events from the day, to
show in my LCD painel 20X4 plugged on usb to a arduino controller.


2017-03-02 12:42 GMT-03:00 Toben Archer <notifications@github.com>:

**Comment by Narcolapser** [comment]
Can you post your code as it is now? I think that shouldn't be to hard to do but it sounds like you've altered the script so seeing it would be very helpful.

**Comment by leonardodutra** [comment]
Hi,

My code is the file named veh.py, i wait to print my scheduled jobs from
the day

python veh.py
Traceback (most recent call last):
  File "veh.py", line 8, in <module>
    vj = json.loads(veh)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2017-03-02 16:06 GMT-03:00 Toben Archer <notifications@github.com>:

**Comment by Narcolapser** [comment]
See, i'm not sure that it will do what you want it to do. That will write a number accounts' calenders out to a file. Try this code:

```
from O365 import *

if __name__ == '__main__':
        e = 'youremail'
        p = 'yourpassword'

        schedule = Schedule((e,p))
        try:
                result = schedule.getCalendars()
                print('Fetched calendars for',e,'was successful:',result)
        except:
                print('Login failed for',e)

        for cal in schedule.calendars:
                print('attempting to fetch events for',e)
                try:
                        result = cal.getEvents()
                        print('Got events',result,'got',len(cal.events))
                except:
                        print('failed to fetch events')
                print('attempting for event information')
                for event in cal.events:
                        print(event)
#To the King!
```

That  is the same basic code, but I removed a bunch of stuff you don't need. You will of course need to replace the lines that say 'youremail' and 'yourpassword' with the appropriate values. Let me know if it works.

**Comment by leonardodutra** [comment]
Hi bro, i am trying to print out the event subject and datetime
unsuccessfully.

('Fetched calendars for', 'leonardo.dutra@xxx.com.br', 'was successful:',
True)
('attempting to fetch events for', 'leonardo.dutra@xxx.com.br')
failed to fetch events
attempting for event information
('attempting to fetch events for', 'leonardo.dutra@xxx.com.br')
failed to fetch events
attempting for event information

there is an event scheduled.

[image: Imagem inline 1]

2017-03-06 11:49 GMT-03:00 Toben Archer <notifications@github.com>:

**Comment by leonardodutra** [comment]
adding a new information,

> /home/leonardo/projetos/python-o365/examples/VehicleBookings/tj.py(29)<module>()
-> result = cal.getEvents()
(Pdb) next
InvalidSchema: InvalidS...pport.',)

**Comment by leonardodutra** [comment]
my proxy server. tks

**Comment by Narcolapser** [comment]
hmm. try this:

```
from O365 import *

if __name__ == '__main__':
        e = 'youremail'
        p = 'yourpassword'

        schedule = Schedule((e,p))
        try:
                result = schedule.getCalendars()
                print('Fetched calendars for',e,'was successful:',result)
        except:
                print('Login failed for',e)

        for cal in schedule.calendars:
                print('attempting to fetch events for',e)
                try:
                        result = cal.getEvents()
                        print('Got events',result,'got',len(cal.events))
                except Exception as exc:
                        print('failed to fetch events: ', exc)
                print('attempting for event information')
                for event in cal.events:
                        print(event)
#To the King!
```

That might give us a better idea of what's going wrong.

**Comment by Narcolapser** [comment]
Hows it going? Or should I just close this?

**Comment by leonardodutra** [comment]
You can close this case. Thank you bro
