### ISSUE TITLE
Pip package Out of Date

### ISSUE THREAD

**Issue by aruvalcaba** [Narcolapser/python-o365#59]
The pip package is out of date. Can someone please update it?

https://pypi.python.org/pypi/O365

Thanks.

**Comment by Narcolapser** [comment]
Yes, there is some updates from #39 I need to work in, but will then be a new version.

**Comment by aruvalcaba** [comment]
@Narcolapser Sounds good, much appreciated!

**Comment by Narcolapser** [comment]
Done.
