### ISSUE TITLE
SSL authentication certificate validation ignore

### ISSUE THREAD

**Issue by mathewfer** [Narcolapser/python-o365#60]
Hi,

Is there a way to set to ignore SSL certificate validation?

Reason is that firewall offers a SSL certificate in the middle. If there is a way to ignore certification validation, that will be great. Otherwise, it works well.

Mathew

**Comment by Narcolapser** [comment]
Can you point to the point in the code you are specifically having a problem with? I'll take a look.

**Comment by mathewfer** [comment]
Hi

Thank you for the reply.

See the Python file below and the SSL error. Note I have removed the
usernames and passwords.

This script works very well from home but not fr.om office where Firewall
send its SSL certificate.

Error - "certificate verify failed"

Even to run pip3, I had to add this "pip3 install --trusted-host
pypi.python.org <package>" to ignore certificate verification test.

If we can do the same tweak here for O365, it will work for O365.

Please let me know whether it is possible and if yes, how to do that.
Thanks in advance.

mathewfer@UBUNTU16SRV:~/scripts$  cat send-mail-o365-1.py
from O365 import Message

def load_html_from_file(path):
    contents = ""
    with open(path, 'r') as f:
        contents = f.read()

    return contents


authenticiation = ("zzzz@yyyyy","XXXX")
m = Message(auth=authenticiation)
m.setRecipients("zzzzz@gmail.com")
m.setSubject("Test 1")
m.setBodyHTML(load_html_from_file("somemsg.html"))
m.sendMessage()
mathewfer@UBUNTU16SRV:~/scripts$

mathewfer@UBUNTU16SRV:~/scripts$ python3 send-mail-o365-2-tested-1.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line
560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line
346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line
787, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 252, in
connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 305, in
ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in
send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line
589, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send-mail-o365-2-tested-1.py", line 17, in <module>
    m.sendMessage()
  File "/usr/local/lib/python3.5/dist-packages/O365/message.py", line 109,
in sendMessage
    self.send_url, data, headers=headers, auth=self.auth)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in
request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in
send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in
send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:645)
mathewfer@UBUNTU16SRV:~/scripts$

**Comment by Narcolapser** [comment]
can you verify for me that pip installs other packages correctly? It sounds like your problem may not be specific to O365.

**Comment by mathewfer** [comment]
H,

Thanks. I will check it again in office on Monday but I checked it on a Linix VM running on my laptop running VMware workstation. Same software run well at home internet connection but failed with the above error at office with SSL certificate verification failure.

By the way, I run this on Python3.

**Comment by mathewfer** [comment]
Hi

I think this comes from "request" module.

Is there a way to do the below in your O365?

"requests.get('https://something.com', **verify=False**)"

**Comment by Narcolapser** [comment]
Well that's a handy feature! I can see plenty of potential reasons for including that. I'll see if I can't add that functionality. 

In the mean time, any luck on the check I requested?

**Comment by mathewfer** [comment]
Thanks. I build another new Ubuntu VM and added Python3 modules. tested at home and in office.

Result;
- It worked at home network - no strict firewall
- It did not work at office network - strict firewall doing traffic decryption. 

Solution; It should pass "verify=False" to O365. 

If you let me know where to add this in your "message.py", I can try to test it and after that you may add it as an additional feature in your O365.

response = requests.get(self.att_url.format(
        self.json['Id']), auth=self.auth

I think it should be here in your file "message.py".

**Comment by mathewfer** [comment]
Hi

Any news/progress in adding for the below;

`requests.get('https://something.com', verify=False)`

Please let me know, if possible, simple change to "message.p" to try this first from my end.

Is this the code line to add to try this? If yes, I can try it.

```
response = requests.get(self.att_url.format(
        self.json['Id']), auth=self.auth, , verify=False)
```
Thanks in advance for your support/response on this

**Comment by Narcolapser** [comment]
Sorry, I've been having some issues getting this library to behave on my new computer. 

I'd like to integrate this with the library as a whole, but I need to figure out how to get the verify to actually work. I'm going to upload a branch with a possible version of this. I'll reference this issue when I push it. Give it a test and let me know if it worked.

**Comment by Narcolapser** [comment]
Try this branch: https://github.com/Narcolapser/python-o365/tree/verifyssl

**Comment by mathewfer** [comment]
Hi

Thanks. tried it and almost there - few errors as below and I tried to fix it but no success.

I believe we are there and just need to check one syntax error - I am trying to check it out

```
mathewfer@UBUNTU16SRV:~/scripts$ python3 send-mail-o365-testing-1.py
Traceback (most recent call last):
  File "send-mail-o365-testing-1.py", line 2, in <module>
    from O365 import Message
  File "/usr/local/lib/python3.5/dist-packages/O365/__init__.py", line 21, in <module>
    from .contact import Contact
  File "/usr/local/lib/python3.5/dist-packages/O365/contact.py", line 41
    self.verify = verify
                       ^
TabError: inconsistent use of tabs and spaces in indentation
mathewfer@UBUNTU16SRV:~/scripts$
```

My script file name is "send-mail-o365-testing-1.py" and contents are;

```
from O365 import Message

def load_html_from_file(path):
    contents = ""
    with open(path, 'r') as f:
        contents = f.read()

    return contents


authenticiation = ("myEmail","Password")
m = Message(auth=authenticiation)
m.setRecipients("senderEmail")
m.setSubject("Test 1")
#m.setBody("Test 1.")
m.setBodyHTML(load_html_from_file("somemsg.html"))
m.sendMessage()
```

Thanks in advance.

**Comment by Narcolapser** [comment]
Sorry for the delay. I've gone through and unified the usage of tabs and spaces. give that branch another try.

**Comment by JMcCoding** [comment]
Hi Narcolapser,

I had a similar issue using the code here:
```
from O365 import Message
authenticiation = ('test@xyz.com','test')
m = Message(auth=authenticiation)
m.setRecipients('receivingtest@xyz.com')
m.setSubject('I made an email script.')
m.setBody('Talk to the computer, cause the human does not want to hear it any more.')
m.sendMessage()
```

```
Traceback (most recent call last):
  File "c:\Software\Scripts\Python\text.py", line 136, in <module>
    m.sendMessage()
  File "C:\Software\Python\lib\site-packages\O365\message.py", line 109, in sendMessage
    self.send_url, data, headers=headers, auth=self.auth)
  File "C:\Software\Python\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Software\Python\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Software\Python\lib\site-packages\requests\sessions.py", line 508, in reque
    resp = self.send(prep, **send_kwargs)
  File "C:\Software\Python\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Software\Python\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='outlook.office365.com', port=4
cate verify failed (_ssl.c:749)'),))
```
I gave that branch a test, and replaced my copy of message.py with it.  Now it sent successfully, when I set the new verify class variable:

```
from O365 import Message
authenticiation = ('test@xyz.com','test')
m = Message(auth=authenticiation)
m.setRecipients('receivingtest@xyz.com')
m.setSubject('I made an email script.')
m.setBody('Talk to the computer, cause the human does not want to hear it any more.')
m.verify = False
m.sendMessage()
```
This is the remaining output, but **it sent successfully**

```
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs
.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

This is an excellent package, and thanks for the work you've put into it.  Since the mathewfer hasn't had a chance to reply, I thought I would.

**Comment by mathewfer** [comment]
Hi 

Sorry for delay in response.
I was away from office but I will test this again on this Monday and let you know - not remote access to this server.

I will report back on Monday.

Yes, this is a great python package getting better and better.

Regards,

Mathew

**Comment by mathewfer** [comment]
Hi Narcolapser,

Still I got some errors, as below and email did not come out. Same script as above.

Also I tried a different script, below and it worked through this firewall. You may be able to spot any issues to fix O365. 

When you do a change, possibly a fix, please let me know and I can now test it quickly in office, within a day.

Again thanks for your package and hope to hear from you soon, possibly with a fix.

#!/usr/bin/env python3

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

username = 'myoffice365email@myCompany.com'  # Email Address from the email you want to send an email
password = 'PWD'  # Password
from_addr = 'myoffice365email@myCompany.com'
to_addrs = 'xyzUssr@gmail.com'
htmlbody = 'somemsg.html'
attachFile = 'email.txt'
emailSubject = 'Test Python'

with open(htmlbody, 'r') as myfile:
    html=myfile.read().replace('\n', '')

# Function that send email.
def send_mail(username, password, from_addr, to_addrs, msg):
    server = smtplib.SMTP('smtp.office365.com')
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login(username, password)
    server.sendmail(from_addr, to_addrs, msg.as_string())
    server.quit()

#for to_addrs in email_list:
msg = MIMEMultipart()
msg['Subject'] = emailSubject
msg['From'] = from_addr
msg['To'] = to_addrs

# Attach HTML to the email
body = MIMEText(html, 'html')
msg.attach(body)

# Attach file to the email
cover_letter = MIMEApplication(open(attachFile, "rb").read())
cover_letter.add_header('Content-Disposition', 'attachment', filename=attachFile)
msg.attach(cover_letter)

try:
    send_mail(username, password, from_addr, to_addrs, msg)
    print ("Email successfully sent to", to_addrs)
except SMTPAuthenticationError:
    print ('SMTPAuthenticationError')
    print ("Email not sent to", to_addrs)

#end

Errors fro O365 branch verifyssl1:

mathewfer@UBUNTU16SRV:~/scripts$ python3 send-mail-o365-testing-2.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /api/v1.0/me/sendmail (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send-mail-o365-testing-2.py", line 18, in <module>
    m.sendMessage()
  File "/usr/local/lib/python3.5/dist-packages/O365/message.py", line 112, in sendMessage
    self.send_url, data, headers=headers, auth=self.auth,verify=self.verify)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /api/v1.0/me/sendmail (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
mathewfer@UBUNTU16SRV:~/scripts$ 

Mathew

**Comment by mathewfer** [comment]
Hi,

My mistake, it got closed but I believe we will be able to get this fixed soon.

Mathew

**Comment by JMcCoding** [comment]
Since you didn't post the updated code, can you make sure you leveraged the new class variable and set

```
(Whatever you named your message).verify = False
```
Before attempting to send?

I'm behind a similar setup, and it ignored the SSL  certificate properly with my above posted code.

**Comment by mathewfer** [comment]
Hi,

Thanks.
Can I please ask exactly where I should set this “.verify = False”? 

In fact, I looked at it too but I could not figure it out.

My tested script is in my previous post if you can help me to find the spot.

Regards,

Mathew

**Comment by JMcCoding** [comment]
I'd add it immediately before m.sendMessage().

This is also assuming your O365->message.py is from the branch Narcolapser had linked.

**Comment by mathewfer** [comment]
Hi 

Thanks.
Yes, I am using the new branch and I will try it tomorrow in office with your addition and let you know the results.

I hope it will work.

Regards,

Mathew

**Comment by Narcolapser** [comment]
Once I have verification I'll merge the branch in and push the changes to pypi.

**Comment by mathewfer** [comment]
Hi

# SUCCESS!! - brilliant work by Narcolapser

See below. All worked as expected and I just had to add line "m.verify = False" above "m.sendMessage()".

Just thinking it would be nice if it is possible to suppress the below output and even as it is just fine.

Thanks a lot for both of your support and sorry for delay in my responses.

When the final one is pushed to pypi, please let us know so we will refresh it to our servers.

Great stuff and great python package. We can close this now.

```
mathew@UBUNTU16SRV:~/scripts$ python3 send-mail-o365-testing-2.py
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
mathew@UBUNTU16SRV:~/scripts$
```

**Comment by Narcolapser** [comment]
I think I'll leave the insecure warning and leave instructions on how to disable it yourself. Reason being 10 and 11 of the zen of python:

> 10. Errors should never pass silently.
> 11. Unless explicitly silenced.

Instruction to suppress the error can be found [here](https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho) but basically work like this:

    import urllib3
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

New version is now up on [pypi](https://pypi.python.org/pypi/O365/0.9.7)
