### ISSUE TITLE
0.9.9 fails upon import -- requests_oauthlib

### ISSUE THREAD

**Issue by joh06937** [Narcolapser/python-o365#70]
$ pip install --user --upgrade O365
Collecting O365
  Downloading O365-0.9.9.tar.gz
Requirement already up-to-date: requests in ./.local/lib/python2.7/site-packages (from O365)
Collecting oauthlib (from O365)
  Downloading oauthlib-2.0.6.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 1.1MB/s
Requirement already up-to-date: idna<2.7,>=2.5 in ./.local/lib/python2.7/site-packages (from requests->O365)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests->O365)
Requirement already up-to-date: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests->O365)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests->O365)
Building wheels for collected packages: O365, oauthlib
  Running setup.py bdist_wheel for O365 ... done
  Stored in directory: .../.cache/pip/wheels/38/17/a1/5b01b96fb0246ae818574def0a4fb4c8570e856cc55e97b8da
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: .../.cache/pip/wheels/e5/46/f7/bb2fde81726295a13a71e3c6396d362ab408921c6562d6efc0
Successfully built O365 oauthlib
Installing collected packages: oauthlib, O365
  Found existing installation: O365 0.9.8
    Uninstalling O365-0.9.8:
      Successfully uninstalled O365-0.9.8
Successfully installed O365-0.9.9 oauthlib-2.0.6

$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import O365
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.local/lib/python2.7/site-packages/O365/__init__.py", line 29, in <module>
    from .connection import Connection
  File ".../.local/lib/python2.7/site-packages/O365/connection.py", line 8, in <module>
    from requests_oauthlib import OAuth2Session
ImportError: No module named requests_oauthlib
\>\>\>

I've removed a few paths and replaced them with "...". Reverting back to 0.9.8 fixes the issue.

**Comment by megadevx** [comment]
I had this same issue.
I manually got the requests_oauthlib with pip. 
pip install requests_oauthlib

**Comment by Narcolapser** [comment]
aaah. Thanks for the tip. I'll throw that dependency into the setup.py and upload a new version as soon as I get back to my desktop.

**Comment by Narcolapser** [comment]
Alright. I just updated the version in pypi. Give it a try and let me know if that works.

**Comment by joh06937** [comment]
Ack, I'm really sorry about forgetting to respond to this.

I did an update from 0.9.8 to the latest and the requests_oauthlib package was pulled in. "python"->"import O365" works fine now!

Thanks for getting to this so quickly (and thanks for making such a useful package)!
