### ISSUE TITLE
tab/spaces update has some errors

### ISSUE THREAD

**Issue by fcollman** [Narcolapser/python-o365#86]
For example.. got this error on an automated build process that made use of this library.

error	27-Feb-2018 09:00:21	  File "/data/notify.py", line 1, in <module>
error	27-Feb-2018 09:00:21	    from O365 import Message
error	27-Feb-2018 09:00:21	  File "/opt/conda/lib/python2.7/site-packages/O365/__init__.py", line 26, in <module>
error	27-Feb-2018 09:00:21	    from .inbox import Inbox
error	27-Feb-2018 09:00:21	  File "/opt/conda/lib/python2.7/site-packages/O365/inbox.py", line 60
error	27-Feb-2018 09:00:21	    try:
error	27-Feb-2018 09:00:21	    ^
error	27-Feb-2018 09:00:21	IndentationError: unexpected indent

**Comment by Narcolapser** [comment]
uploaded new version, thanks for the fix.
