### ISSUE TITLE
Setting Message-ID

### ISSUE THREAD

**Issue by dr-bob-price** [Narcolapser/python-o365#88]
Apologies for posting this here but i've had no luck finding out the answer elsewhere.

Is there any way to set the Message ID when posting to o365? 

I've tried this:

m.json['Message-ID']=message_id

But it appears Microsoft just ignore it??

Cheers,
Rob

**Comment by Narcolapser** [comment]
Posting such questions here is perfectly fine. 

So far as I am aware such is not possible. As I understand it Message ID is a unique identifier that MS uses to to identify your message. Any attempt to change it could result in a collision. 

But I may be miss understanding. What are you trying to accomplish by changing the Message ID?

**Comment by dr-bob-price** [comment]
I'm running an open source ERP (Odoo) that uses the message-id. I have it working using other SMTP (using smtplib) servers, but o365 seems to do it's own thing. Does microsoft not adhere to the standards everyone else uses. I appreciate you are not a Microsoft expert, but I don't know where else to ask!
Thanks, for the help.
Rob

**Comment by Narcolapser** [comment]
Aaah, ok, the thing is this isn't SMTP. This is REST. The protocol is all basically http requests with json packages. The API built on those protocols is unique. Some day we may have a standard REST API for email, but right now such a thing doesn't exist. So yes, you are right that O365 does it's own thing, at least when it is concerning the REST API. This library I've made only concerns itself with the REST API and not SMTP. You can probably get O365 to work the way you want it to, but you'll need to use a lib that does SMTP. 

Glad to help. Feel free to keep asking questions.
